#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinTokensPoker.Resource", IsApplication=true)]

namespace XamarinTokensPoker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int theme_devicedefault_background = 2131165184;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int buttonstyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int startbuttonstyle = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08001d
			public const int Bid = 2131230749;
			
			// aapt resource value: 0x7f08001f
			public const int Call = 2131230751;
			
			// aapt resource value: 0x7f08001e
			public const int CheckButton = 2131230750;
			
			// aapt resource value: 0x7f080005
			public const int EnterName = 2131230725;
			
			// aapt resource value: 0x7f08001a
			public const int LayoutId = 2131230746;
			
			// aapt resource value: 0x7f080026
			public const int MyButton = 2131230758;
			
			// aapt resource value: 0x7f080028
			public const int NewGameButton = 2131230760;
			
			// aapt resource value: 0x7f080020
			public const int Pass = 2131230752;
			
			// aapt resource value: 0x7f080021
			public const int Rise = 2131230753;
			
			// aapt resource value: 0x7f08001b
			public const int Round = 2131230747;
			
			// aapt resource value: 0x7f080027
			public const int ShowWinnerText = 2131230759;
			
			// aapt resource value: 0x7f08000f
			public const int Text = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int Text1 = 2131230736;
			
			// aapt resource value: 0x7f08001c
			public const int activPlayer = 2131230748;
			
			// aapt resource value: 0x7f080023
			public const int actualblindtxt = 2131230755;
			
			// aapt resource value: 0x7f080001
			public const int addplayerEdittext = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int addplayerbutton = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int cashforeveryoneEditText = 2131230726;
			
			// aapt resource value: 0x7f080016
			public const int chooseadapter = 2131230742;
			
			// aapt resource value: 0x7f080018
			public const int content_frame = 2131230744;
			
			// aapt resource value: 0x7f080009
			public const int createplayersListView = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int gotoTableButton = 2131230731;
			
			// aapt resource value: 0x7f080012
			public const int layoutwinner = 2131230738;
			
			// aapt resource value: 0x7f080025
			public const int leftListView = 2131230757;
			
			// aapt resource value: 0x7f080019
			public const int listView1 = 2131230745;
			
			// aapt resource value: 0x7f080017
			public const int myDrawer = 2131230743;
			
			// aapt resource value: 0x7f08000a
			public const int newPlayerButton = 2131230730;
			
			// aapt resource value: 0x7f080015
			public const int nextroundbutton = 2131230741;
			
			// aapt resource value: 0x7f08000d
			public const int numberPicker1 = 2131230733;
			
			// aapt resource value: 0x7f080004
			public const int playercashtowinseekbar = 2131230724;
			
			// aapt resource value: 0x7f080029
			public const int playercashtowintext = 2131230761;
			
			// aapt resource value: 0x7f080003
			public const int playercashtowintextseekbar = 2131230723;
			
			// aapt resource value: 0x7f080011
			public const int playerstodeletelistview = 2131230737;
			
			// aapt resource value: 0x7f080024
			public const int roundpot = 2131230756;
			
			// aapt resource value: 0x7f080022
			public const int seekBar1 = 2131230754;
			
			// aapt resource value: 0x7f080008
			public const int smallblindforstart = 2131230728;
			
			// aapt resource value: 0x7f080000
			public const int textView1 = 2131230720;
			
			// aapt resource value: 0x7f080007
			public const int textView2 = 2131230727;
			
			// aapt resource value: 0x7f08000c
			public const int textView3 = 2131230732;
			
			// aapt resource value: 0x7f08000e
			public const int textView4 = 2131230734;
			
			// aapt resource value: 0x7f080014
			public const int winnerlistview = 2131230740;
			
			// aapt resource value: 0x7f080013
			public const int winnertext = 2131230739;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddPlayer = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Choosewinnerseekbar = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CreatePlayerLayAdapter = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CreatePlayers = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CustomViewaxml = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Deleteplayer = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int FlopLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int GameScreen = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ShowWinner = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int WinnerView = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int test = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int StartGameButton = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int close_drawer = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int open_drawer = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060004
			public const int Theme_Custom = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int button_text = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int createplayeroff_text = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int createplayeron_text = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int mainscreen_text = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
